name: Roger's Blog
description: Análise de protocolos, Linux, etc
meta_description: Roger's Blog. Network, Linux, SDN.
#date: 2012
permalink: /:year/:month/:day/:title

markdown: kramdown
highlighter: rouge

logo: false
paginate: 15
baseurl: /
domain_name: 'comprar posteriormente um dominio'
google_analytics: 'UA-xx-xx-xx-xx'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            '/'
author:         'Roger Ribeiro'
